[2025-03-15T10:05:45.336+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-15T10:05:45.343+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training-pipeline.validation manual__2025-03-15T10:05:27.735476+00:00 [queued]>
[2025-03-15T10:05:45.346+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training-pipeline.validation manual__2025-03-15T10:05:27.735476+00:00 [queued]>
[2025-03-15T10:05:45.346+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-15T10:05:45.350+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): validation> on 2025-03-15 10:05:27.735476+00:00
[2025-03-15T10:05:45.353+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=171) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-15T10:05:45.354+0000] {standard_task_runner.py:72} INFO - Started process 181 to run task
[2025-03-15T10:05:45.354+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'training-pipeline', 'validation', 'manual__2025-03-15T10:05:27.735476+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline.py', '--cfg-path', '/tmp/tmpu97t58b9']
[2025-03-15T10:05:45.356+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask validation
[2025-03-15T10:05:45.371+0000] {task_command.py:467} INFO - Running <TaskInstance: training-pipeline.validation manual__2025-03-15T10:05:27.735476+00:00 [running]> on host dfe125e804f7
[2025-03-15T10:05:45.395+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='training-pipeline' AIRFLOW_CTX_TASK_ID='validation' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T10:05:27.735476+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T10:05:27.735476+00:00'
[2025-03-15T10:05:45.396+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-15T10:05:45.401+0000] {training_pipeline.py:93} INFO - Attempting to fetch config from XCom for run_id: {'mlflow_run_id': '26656eb25b924ea485aacc57a2ae92cf'}
[2025-03-15T10:05:45.403+0000] {training_pipeline.py:100} INFO - Configuration loaded successfully from XCom: {'mlflow': {'registered_model_name': 'cancellation_estimator', 'tracking_uri': 'http://mlflow-server:5500', 'artifact_location': 'mlflow/cancellation_estimator', 's3_endpoint_url': 'http://minio:9000', 'bucket': 'mlflow'}, 'kafka': {'bootstrap_servers': 'pkc-921jm.us-east-2.aws.confluent.cloud:9092', 'username': 'N2I6QDSAFXKGXQJX', 'password': 'f+T6MLkzJMhrY1Xo9UMZ2WNMpWn2lP8ki+bU3LAXYTRplGK2eV2jXWKQxEQguFDz', 'topic': 'fraud_topic_1', 'output_topic': 'fraud_alert'}}
[2025-03-15T10:05:45.403+0000] {condition_step.py:38} INFO - Run_id: {'mlflow_run_id': '26656eb25b924ea485aacc57a2ae92cf'}
[2025-03-15T10:05:45.404+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/training_pipeline.py", line 111, in condition_step_task_callable
    condition_step(mlflow_run_id)
  File "/opt/airflow/dags/steps/condition_step.py", line 42, in __call__
    run = mlflow.get_run(run_id=mlflow_run_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 675, in get_run
    return MlflowClient().get_run(run_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 251, in get_run
    return self._tracking_client.get_run(run_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 106, in get_run
    _validate_run_id(run_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/validation.py", line 391, in _validate_run_id
    if _RUN_ID_REGEX.match(run_id) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'dict'
[2025-03-15T10:05:45.411+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=training-pipeline, task_id=validation, run_id=manual__2025-03-15T10:05:27.735476+00:00, execution_date=20250315T100527, start_date=20250315T100545, end_date=20250315T100545
[2025-03-15T10:05:45.420+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-15T10:05:45.420+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 83 for task validation (expected string or bytes-like object, got 'dict'; 181)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/training_pipeline.py", line 111, in condition_step_task_callable
    condition_step(mlflow_run_id)
  File "/opt/airflow/dags/steps/condition_step.py", line 42, in __call__
    run = mlflow.get_run(run_id=mlflow_run_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 675, in get_run
    return MlflowClient().get_run(run_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 251, in get_run
    return self._tracking_client.get_run(run_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 106, in get_run
    _validate_run_id(run_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/validation.py", line 391, in _validate_run_id
    if _RUN_ID_REGEX.match(run_id) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'dict'
[2025-03-15T10:05:45.455+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-15T10:05:45.462+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-15T10:05:45.462+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
