[2025-03-15T03:35:31.992+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:35:31.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:35:31.994+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:35:31.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:35:31.997+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:35:31.996+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:35:31.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:35:32.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.024 seconds
[2025-03-15T03:36:02.299+0000] {processor.py:186} INFO - Started process (PID=336) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:36:02.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:36:02.303+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:36:02.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:36:02.307+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:36:02.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:36:02.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:36:02.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.034 seconds
[2025-03-15T03:36:32.600+0000] {processor.py:186} INFO - Started process (PID=364) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:36:32.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:36:32.608+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:36:32.607+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:36:32.618+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:36:32.617+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:36:32.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:36:32.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.045 seconds
[2025-03-15T03:37:19.474+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:37:19.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:37:19.476+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:37:19.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:37:19.482+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:37:19.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:37:19.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:37:19.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.030 seconds
[2025-03-15T03:37:49.822+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:37:49.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:37:49.827+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:37:49.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:37:49.841+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:37:49.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:37:49.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:37:49.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.042 seconds
[2025-03-15T03:38:20.785+0000] {processor.py:186} INFO - Started process (PID=103) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:38:20.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:38:20.790+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:38:20.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:38:20.796+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:38:20.794+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:38:20.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:38:20.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.057 seconds
[2025-03-15T03:38:51.116+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:38:51.117+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:38:51.121+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:38:51.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:38:51.128+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:38:51.125+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:38:51.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:38:51.143+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.035 seconds
[2025-03-15T03:39:21.414+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:39:21.416+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:39:21.420+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:39:21.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:39:21.425+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:39:21.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:39:21.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:39:21.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.057 seconds
[2025-03-15T03:39:51.741+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:39:51.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:39:51.743+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:39:51.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:39:51.746+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:39:51.746+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:39:51.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:39:51.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.022 seconds
[2025-03-15T03:40:22.029+0000] {processor.py:186} INFO - Started process (PID=211) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:40:22.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:40:22.039+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:40:22.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:40:22.043+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:40:22.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:40:22.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:40:22.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.035 seconds
[2025-03-15T03:40:52.311+0000] {processor.py:186} INFO - Started process (PID=238) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:40:52.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:40:52.317+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:40:52.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:40:52.325+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:40:52.323+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:40:52.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:40:52.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.045 seconds
[2025-03-15T03:41:22.674+0000] {processor.py:186} INFO - Started process (PID=265) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:41:22.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:41:22.678+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:41:22.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:41:22.685+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:41:22.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:41:22.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:41:22.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.043 seconds
[2025-03-15T03:41:23.693+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:41:23.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:41:23.698+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:41:23.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:41:23.704+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:41:23.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:41:23.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:41:23.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.030 seconds
[2025-03-15T03:41:53.986+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:41:53.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:41:53.989+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:41:53.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:41:53.995+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:41:53.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:41:53.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:41:54.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.029 seconds
[2025-03-15T03:42:24.346+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:42:24.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:42:24.348+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:42:24.348+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:42:24.351+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:42:24.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:42:24.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:42:24.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.018 seconds
[2025-03-15T03:42:54.588+0000] {processor.py:186} INFO - Started process (PID=353) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:42:54.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:42:54.592+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:42:54.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:42:54.597+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:42:54.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:42:54.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:42:54.614+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.033 seconds
[2025-03-15T03:43:24.908+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:43:24.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:43:24.910+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:43:24.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:43:24.914+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:43:24.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:43:24.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:43:24.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.025 seconds
[2025-03-15T03:43:55.050+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:43:55.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:43:55.053+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:43:55.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:43:55.057+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:43:55.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:43:55.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:43:55.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.031 seconds
[2025-03-15T03:44:25.368+0000] {processor.py:186} INFO - Started process (PID=433) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:44:25.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:44:25.373+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:44:25.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:44:25.379+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:44:25.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:44:25.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:44:25.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.039 seconds
[2025-03-15T03:44:55.700+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:44:55.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:44:55.709+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:44:55.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:44:55.715+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:44:55.714+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T03:44:55.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:44:55.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.042 seconds
[2025-03-15T03:45:23.064+0000] {processor.py:186} INFO - Started process (PID=480) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:45:23.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T03:45:23.068+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:45:23.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:45:23.070+0000] {logging_mixin.py:190} INFO - [2025-03-15T03:45:23.070+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/steps/inference_step.py assumed to contain no DAGs. Skipping.
[2025-03-15T03:45:23.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T03:45:23.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.048 seconds
[2025-03-15T05:48:07.625+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:48:07.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:48:07.628+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:48:07.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:48:07.972+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:48:07.971+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 7, in <module>
    from steps.inference_step import InferenceStep
  File "/opt/airflow/dags/steps/inference_step.py", line 7, in <module>
    from steps.inference_step import InferenceStep
ImportError: cannot import name 'InferenceStep' from partially initialized module 'steps.inference_step' (most likely due to a circular import) (/opt/airflow/dags/steps/inference_step.py)
[2025-03-15T05:48:07.972+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:48:07.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.356 seconds
[2025-03-15T05:48:38.262+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:48:38.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:48:38.265+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:48:38.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:48:38.623+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:48:38.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 7, in <module>
    from steps.inference_step import InferenceStep
  File "/opt/airflow/dags/steps/inference_step.py", line 7, in <module>
    from steps.inference_step import InferenceStep
ImportError: cannot import name 'InferenceStep' from partially initialized module 'steps.inference_step' (most likely due to a circular import) (/opt/airflow/dags/steps/inference_step.py)
[2025-03-15T05:48:38.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:48:38.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.377 seconds
[2025-03-15T05:49:08.902+0000] {processor.py:186} INFO - Started process (PID=346) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:49:08.903+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:49:08.904+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:49:08.904+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:49:09.250+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:49:09.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 7, in <module>
    from steps.inference_step import InferenceStep
  File "/opt/airflow/dags/steps/inference_step.py", line 7, in <module>
    from steps.inference_step import InferenceStep
ImportError: cannot import name 'InferenceStep' from partially initialized module 'steps.inference_step' (most likely due to a circular import) (/opt/airflow/dags/steps/inference_step.py)
[2025-03-15T05:49:09.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:49:09.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.359 seconds
[2025-03-15T05:49:39.549+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:49:39.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:49:39.551+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:49:39.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:49:39.926+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:49:39.925+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 7, in <module>
    from steps.inference_step import InferenceStep
  File "/opt/airflow/dags/steps/inference_step.py", line 7, in <module>
    from steps.inference_step import InferenceStep
ImportError: cannot import name 'InferenceStep' from partially initialized module 'steps.inference_step' (most likely due to a circular import) (/opt/airflow/dags/steps/inference_step.py)
[2025-03-15T05:49:39.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:49:39.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.390 seconds
[2025-03-15T05:50:00.124+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:50:00.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:50:00.126+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:50:00.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:50:00.133+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:50:00.131+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/steps/inference_step.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/steps/inference_step.py", line 6, in <module>
    from preprocess_step import PreprocessStep
ModuleNotFoundError: No module named 'preprocess_step'
[2025-03-15T05:50:00.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:50:00.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.028 seconds
[2025-03-15T05:50:26.866+0000] {processor.py:186} INFO - Started process (PID=408) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:50:26.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:50:26.868+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:50:26.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:50:26.870+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:50:26.870+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/steps/inference_step.py assumed to contain no DAGs. Skipping.
[2025-03-15T05:50:26.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:50:26.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.025 seconds
[2025-03-15T05:50:57.031+0000] {processor.py:186} INFO - Started process (PID=426) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:50:57.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:50:57.039+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:50:57.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:50:57.041+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:50:57.041+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/steps/inference_step.py assumed to contain no DAGs. Skipping.
[2025-03-15T05:50:57.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:50:57.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.033 seconds
[2025-03-15T05:51:27.158+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:51:27.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:51:27.161+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:51:27.160+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:51:27.163+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:51:27.163+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/steps/inference_step.py assumed to contain no DAGs. Skipping.
[2025-03-15T05:51:27.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:51:27.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.029 seconds
[2025-03-15T05:51:57.290+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:51:57.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:51:57.293+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:51:57.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:51:57.294+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:51:57.294+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/steps/inference_step.py assumed to contain no DAGs. Skipping.
[2025-03-15T05:51:57.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:51:57.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.017 seconds
[2025-03-15T05:52:27.542+0000] {processor.py:186} INFO - Started process (PID=488) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:52:27.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:52:27.543+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:52:27.543+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:52:27.544+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:52:27.544+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/steps/inference_step.py assumed to contain no DAGs. Skipping.
[2025-03-15T05:52:27.545+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:52:27.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.016 seconds
[2025-03-15T05:52:57.836+0000] {processor.py:186} INFO - Started process (PID=515) to work on /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:52:57.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/steps/inference_step.py for tasks to queue
[2025-03-15T05:52:57.838+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:52:57.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:52:57.840+0000] {logging_mixin.py:190} INFO - [2025-03-15T05:52:57.840+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/steps/inference_step.py assumed to contain no DAGs. Skipping.
[2025-03-15T05:52:57.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/steps/inference_step.py
[2025-03-15T05:52:57.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/steps/inference_step.py took 0.023 seconds
